baseURL = "https://autocal.berkeley.edu/"
#languageCode = "en-us"
#title = "UC Berkeley Autonomous Systems Compeition Team | AutoCAL"
title = "AutoCAL"
theme = "hyde"
canonifyURLs = false
relativeurl = true


[Params]
    description = "UC Berkeley Autonomous Systems Competition Team"
